kind: pipeline
name: default
workspace:
    base: /go
    path: src/k8s.io/kubernetes

steps:
- name: build
  image: fanux/kubernetes-build:v1.0.0
  commands:
      #    - make all WHAT=cmd/kubeadm GOFLAGS=-v
      - KUBE_GIT_TREE_STATE="clean" KUBE_GIT_VERSION=v1.13.4 KUBE_BUILD_PLATFORMS=linux/amd64 make all WHAT=cmd/kubeadm GOFLAGS=-v

- name: publish
  image: plugins/github-release
  settings:
    api_key: 
        from_secret: git-release-token
    files: _output/local/bin/linux/amd64/kubeadm 
    title: ${DRONE_TAG}
    note: Note.md
    when:
        event: tag
