kind: pipeline
name: default
workspace:
    base: /go
    path: src/k8s.io/kubernetes

steps:
- name: build
  image: fanux/kube-build:v1.12.1-2 
  environment: 
    GO111MODULE: on
  commands:
      - make generated_files UPDATE_API_KNOWN_VIOLATIONS=true
      - KUBE_GIT_TREE_STATE="clean" KUBE_GIT_VERSION=v1.14.0 KUBE_BUILD_PLATFORMS=linux/amd64 make all WHAT=cmd/kubelet GOFLAGS=-v
      - ls  _output/bin/

- name: publish
  image: plugins/github-release
  settings:
    api_key: 
        from_secret: git-release-token
    files: _output/bin/kubelet
    title: ${DRONE_TAG}
    note: Note.md
    when:
        event: tag
