kind: pipeline
name: default

steps:
- name: build
  image: fanux/kubernetes-build:v1.0.0
  commands:
    - make all WHAT=cmd/kubeadm GOFLAGS=-v

- name: publish
  image: plugins/github-release
  settings:
    api_key: 
        from_secret: git-release-token
    files: _output/local/bin/linux/amd64/kubeadm 
    title: ${DRONE_COMMIT_MESSAGE}
    note: CHANGELOG.md
